---
apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: dns
  labels:
    app: pihole
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.231
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 53
    targetPort: 53
    protocol: TCP
    name: dns-tcp
  - port: 53
    targetPort: 53
    protocol: UDP
    name: dns-udp
  selector:
    app: pihole

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-dns-config
  namespace: dns
data:
  custom-dns-entries: |
    192.168.0.231 pihole.homelab.

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-upstream-dns
  namespace: dns
data:
  01-upstream-dns: |
    server=8.8.8.8
    server=8.8.4.4

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-interface-settings
  namespace: dns
data:
  02-bind-interface: |
    interface=eth0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: dns
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
      # annotations:
      #   vault.hashicorp.com/agent-inject: 'true'
      #   vault.hashicorp.com/tls-skip-verify: "true"
      #   vault.hashicorp.com/role: 'dns-app'
      #   vault.hashicorp.com/agent-inject-secret-config: 'secret/data/kubernetes/pihole'
      #   vault.hashicorp.com/agent-inject-template-config: |
      #     {{ with secret "secret/data/kubernetes/pihole" -}}
      #       export WEBPASSWORD="{{ .Data.data.password }}"
      #     {{- end }}
    spec:
      serviceAccountName: internal-app
      containers:
      - name: pihole
        image: pihole/pihole:2024.07.0
        resources:
          requests:
            cpu: "50m"
            memory: "32Mi"
          limits:
            cpu: "100m"
            memory: "64Mi"
        ports:
        - containerPort: 80
          name: http
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        volumeMounts:
        - name: custom-dns-config
          mountPath: /etc/pihole/custom.list
          subPath: custom-dns-entries
        - name: upstream-dns-config
          mountPath: /etc/dnsmasq.d/01-upstream-dns.conf
          subPath: 01-upstream-dns
        - name: interface-settings-config
          mountPath: /etc/dnsmasq.d/02-bind-interface.conf
          subPath: 02-bind-interface
        - name: pihole-secret
          mountPath: '/mnt/secrets-store'
          readOnly: true
        - name: vault-dns-creds-2
          mountPath: /k8s-secret
          readOnly: true
        env:
        - name: TZ
          value: "Asia/Tokyo"
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole-secret
              key: password
      volumes:
      - name: custom-dns-config
        configMap:
          name: pihole-dns-config
      - name: upstream-dns-config
        configMap:
          name: pihole-upstream-dns
      - name: interface-settings-config
        configMap:
          name: pihole-interface-settings
      - name: pihole-secret
        csi:
          driver: 'secrets-store.csi.k8s.io'
          readOnly: true
          volumeAttributes:
            secretProviderClass: pihole-secret
      - name: vault-dns-creds-2
        secret:
          secretName: pihole-secret
