---
- name: Install
  ansible.builtin.include_tasks:
    file: install.yaml

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yaml

- name: Start and enable Grafana service
  become: true
  ansible.builtin.systemd:
    name: grafana-server
    enabled: true
    state: started
    daemon_reload: true
