---
- name: Install
  ansible.builtin.import_tasks:
    file: install.yml

- name: Copy Coredns file
  ansible.builtin.template:
    src: Corefile.j2
    dest: /etc/coredns/Corefile
    owner: root
    group: root
    mode: "0644"
  become: true
  notify:
    - restart coredns

- name: Start and enable CoreDNS
  become: true
  ansible.builtin.systemd:
    name: coredns
    enabled: true
    state: started
    daemon_reload: true
