apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-configmap
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS keycloak;
    GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;


# SealedSecretsなどで改善する
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  mariadb-user-password: cGFzc3dvcmQ= # echo -n 'password'|base64

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
      name: mariadb-port
  clusterIP: None
  selector:
    app: mariadb

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-sts
spec:
  serviceName: "mariadb-service"
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      restartPolicy: Always
      containers:
        - name: mariadb
          image: mariadb
          ports:
            - containerPort: 3306
              name: mariadb-port
          env:
            - name: MARIADB_USER
              value: user
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-user-password
            - name: MARIADB_RANDOM_ROOT_PASSWORD
              value: "1"
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /var/lib/mysql
              subPath: data
            - name: sql-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: sql-init
          configMap:
            name: mariadb-configmap
            items:
              - key: init.sql
                path: init.sql
  volumeClaimTemplates:
    - metadata:
        name: mariadb-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
