---	
# MetalLB test	
apiVersion: v1	
kind: Service	
metadata:	
  name: nginx-svc	
  namespace: metallb-system
spec:	
  selector:	
    app: nginx	
  ports:	
  - protocol: TCP	
    port: 80	
    targetPort: 80	
  type: LoadBalancer	
  loadBalancerIP: 192.168.0.239

---	
apiVersion: apps/v1	
kind: Deployment	
metadata:	
  name: nginx
  namespace: metallb-system
spec:	
  selector:	
    matchLabels:	
      app: nginx	
  replicas: 2	
  template:	
    metadata:	
      labels:	
        app: nginx	
    spec:	
      containers:	
      - name: nginx	
        image: nginx:1.14.2	
        ports:	
        - containerPort: 80	
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "50m"
