---
- name: Configure Grafana
  become: true
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: grafana
    group: grafana
    mode: "0644"
  notify:
    - reload grafana
