- name: Install nessesary package
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gnupg
    update_cache: true

- name: Add grafana gpg key
  shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

- name: Add grafana repo
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: Install Grafana
  ansible.builtin.apt:
    name:
      - grafana

- name: Configure Grafana
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: grafana
    group: grafana
    mode: "0644"

- name: Start and enable Grafana service
  ansible.builtin.systemd:
    name: grafana-server
    enabled: true
    state: started
