- name: Add grafana gpg key
  become: true
  ansible.builtin.get_url:
    url: https://packages.grafana.com/gpg.key
    dest: /etc/apt/keyrings/grafana.asc
    mode: '0644'
    force: true

- name: Add grafana repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/grafana.asc] https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: Install Grafana
  become: true
  ansible.builtin.apt:
    name:
      - grafana

- name: Configure Grafana
  become: true
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: grafana
    group: grafana
    mode: "0644"

- name: Start and enable Grafana service
  become: true
  ansible.builtin.systemd:
    name: grafana-server
    enabled: true
    state: started
