services:
  mariadb:
    image: mariadb
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/init:/docker-entrypoint-initdb.d
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_USER: user
      MARIADB_PASSWORD: password

  nextcloud:
    image: nextcloud:28.0.1-apache
    depends_on:
      - mariadb
    volumes:
      - ./nextcloud/html:/var/www/html
    ports:
      - 8080:80
    environment:
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
