---
k3s_cluster:
  children:
    k3s_cluster_server:
      hosts:
        192.168.0.110:
    k3s_cluster_agent:
      hosts:
        192.168.0.111:
        192.168.0.112:
  # Required Vars
  vars:
    # token: "changeme!"
    api_endpoint: "{{ hostvars[groups['k3s_cluster_server'][0]]['ansible_host'] | default(groups['k3s_cluster_server'][0]) }}"

k3s_stg_cluster:
  children:
    k3s_stg_cluster_server:
      hosts:
        192.168.0.120:
  # Required Vars
  vars:
    # token: "changeme!"
    api_endpoint: "{{ hostvars[groups['k3s_stg_cluster_server'][0]]['ansible_host'] | default(groups['k3s_stg_cluster_server'][0]) }}"
