---
k3s_cluster:
  children:
    server:
      hosts:
        192.168.0.110:
    agent:
      hosts:
        192.168.0.111:
        192.168.0.112:
  # Required Vars
  vars:
    # token: "changeme!"
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"

k3s_stg_cluster:
  children:
    server:
      hosts:
        192.168.0.120:
  # Required Vars
  vars:
    # token: "changeme!"
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
