apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pihole-secret
  namespace: dns
spec:
  provider: vault
  secretObjects:
    - secretName: pihole-secret
      type: Opaque
      data:
        - objectName: obj-password
          key: password
  parameters:
    vaultAddress: "https://192.168.0.211:8200"
    vaultSkipTLSVerify: "true"
    roleName: "dns-app"
    objects: |
      - objectName: "obj-password"
        secretPath: "secret/data/kubernetes/pihole"
        secretKey: "password"
