- name: Install Prometheus
  ansible.builtin.apt:
    name:
      - prometheus
  become: true

- name: Configure Prometheus
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: "0644"

- name: Start and enable Prometheus service
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    state: started
  become: true
