---
- name: Install
  ansible.builtin.import_tasks:
    file: install.yml

# Sep 10 01:27:49 homedns coredns[3605]: loading Caddyfile via flag: open /etc/coredns/Corefile: no such fi>

- name: Start and enable CoreDNS
  become: true
  ansible.builtin.systemd:
    name: coredns
    enabled: true
    state: started
    daemon_reload: true
