alertmanager:
  alertmanagerSpec:
    nodeSelector:
      kubernetes.io/role: worker
grafana:
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.0.232
  nodeSelector:
    kubernetes.io/role: worker
prometheus:
  prometheusSpec:
    nodeSelector:
      kubernetes.io/role: worker
